# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='message',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\x07message\"\x9a\x01\n\tIDRequest\x12\x11\n\trequestID\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x12\x38\n\x0buserHeaders\x18\x0e \x03(\x0b\x32#.message.IDRequest.UserHeadersEntry\x1a\x32\n\x10UserHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1a\n\x07IDReply\x12\x0f\n\x07message\x18\x01 \x01(\t2B\n\x0bInformation\x12\x33\n\tRequestID\x12\x12.message.IDRequest\x1a\x10.message.IDReply\"\x00\x62\x06proto3'
)




_IDREQUEST_USERHEADERSENTRY = _descriptor.Descriptor(
  name='UserHeadersEntry',
  full_name='message.IDRequest.UserHeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='message.IDRequest.UserHeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='message.IDRequest.UserHeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=181,
)

_IDREQUEST = _descriptor.Descriptor(
  name='IDRequest',
  full_name='message.IDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestID', full_name='message.IDRequest.requestID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='message.IDRequest.body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userHeaders', full_name='message.IDRequest.userHeaders', index=2,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_IDREQUEST_USERHEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=181,
)


_IDREPLY = _descriptor.Descriptor(
  name='IDReply',
  full_name='message.IDReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='message.IDReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=209,
)

_IDREQUEST_USERHEADERSENTRY.containing_type = _IDREQUEST
_IDREQUEST.fields_by_name['userHeaders'].message_type = _IDREQUEST_USERHEADERSENTRY
DESCRIPTOR.message_types_by_name['IDRequest'] = _IDREQUEST
DESCRIPTOR.message_types_by_name['IDReply'] = _IDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IDRequest = _reflection.GeneratedProtocolMessageType('IDRequest', (_message.Message,), {

  'UserHeadersEntry' : _reflection.GeneratedProtocolMessageType('UserHeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _IDREQUEST_USERHEADERSENTRY,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:message.IDRequest.UserHeadersEntry)
    })
  ,
  'DESCRIPTOR' : _IDREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.IDRequest)
  })
_sym_db.RegisterMessage(IDRequest)
_sym_db.RegisterMessage(IDRequest.UserHeadersEntry)

IDReply = _reflection.GeneratedProtocolMessageType('IDReply', (_message.Message,), {
  'DESCRIPTOR' : _IDREPLY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:message.IDReply)
  })
_sym_db.RegisterMessage(IDReply)


_IDREQUEST_USERHEADERSENTRY._options = None

_INFORMATION = _descriptor.ServiceDescriptor(
  name='Information',
  full_name='message.Information',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=211,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestID',
    full_name='message.Information.RequestID',
    index=0,
    containing_service=None,
    input_type=_IDREQUEST,
    output_type=_IDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INFORMATION)

DESCRIPTOR.services_by_name['Information'] = _INFORMATION

# @@protoc_insertion_point(module_scope)
