# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class InformationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestID = channel.unary_unary(
                '/message.Information/RequestID',
                request_serializer=message__pb2.IDRequest.SerializeToString,
                response_deserializer=message__pb2.IDReply.FromString,
                )


class InformationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InformationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestID': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestID,
                    request_deserializer=message__pb2.IDRequest.FromString,
                    response_serializer=message__pb2.IDReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.Information', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Information(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.Information/RequestID',
            message__pb2.IDRequest.SerializeToString,
            message__pb2.IDReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
